const mdata = [
    {
        id : 1,
        imgsrc : "https://image-cdn.essentiallysports.com/wp-content/uploads/DJ-Black-Adam.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 2,
        imgsrc : "https://upload.wikimedia.org/wikipedia/en/a/a9/Black_Adam_%28film%29_poster.jpg" ,
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 3,
        imgsrc : "https://marveldccrossover.com/wp-content/uploads/2021/10/a7353190b6217bc273c21bcfbec2c9be-1.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 4,
        imgsrc : "https://i.pinimg.com/736x/8f/c2/d7/8fc2d70bce28ed1fefdae2f49e133f92.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 5,
        imgsrc : "https://image-cdn.essentiallysports.com/wp-content/uploads/DJ-Black-Adam.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 6,
        imgsrc : "https://upload.wikimedia.org/wikipedia/en/a/a9/Black_Adam_%28film%29_poster.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 7,
        imgsrc : "https://marveldccrossover.com/wp-content/uploads/2021/10/a7353190b6217bc273c21bcfbec2c9be-1.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 8,
        imgsrc : "https://i.pinimg.com/736x/8f/c2/d7/8fc2d70bce28ed1fefdae2f49e133f92.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 9,
        imgsrc : "https://image-cdn.essentiallysports.com/wp-content/uploads/DJ-Black-Adam.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 10,
        imgsrc : "https://upload.wikimedia.org/wikipedia/en/a/a9/Black_Adam_%28film%29_poster.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 11,
        imgsrc : "https://marveldccrossover.com/wp-content/uploads/2021/10/a7353190b6217bc273c21bcfbec2c9be-1.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
    {
        id : 12,
        imgsrc : "https://i.pinimg.com/736x/8f/c2/d7/8fc2d70bce28ed1fefdae2f49e133f92.jpg",
        dres : "Original Netfliex Cinema",
        title : "Black Adam",
        link : "https://www.youtube.com/watch?v=X0tOpBuYasI",
    },
];
export default mdata;